Message improvement
PatrykMargasinski/MafiaAPI pull request #21
Opened 2021-07-22 18:18 UTC by PatrykMargasinski

Added new variables for message model (ReceiveDate, Seen, Subject)
Added hash and encryption methods

2021-07-22 19:45 UTC, krzysztofMi requested changes
I request changes. Some of them maybe are not needed, if you think some comments are not correct, please respond to them 🦅.

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Controllers/MessageController.cs
> +        [HttpGet("{id}")]
This should throw an exception because there are two endpoints with the same name now, or even more.  Try use `localhost:xxxx/message/1` in your web browser when backend server is running and see what happen. Coming into conclusion, this {id} annotation is not necessary here.

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Controllers/MessageController.cs
> +            var content= _securityService.Decrypt(message.Subject)+"\n\n"+
`_securityService.Decrypt(message.Subject) + "\n\n" +` no spaces :) Maybe we should also put some Linter into our actions :D

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Controllers/MessageController.cs
> +        public JsonResult DeleteMessages(string stringIds)
Is it working? stringIds is query parameter or something like that? 
Maybe [link](https://stackoverflow.com/questions/309115/how-can-i-post-an-array-of-string-to-asp-net-mvc-controller-without-a-form) this solution will be better.

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Controllers/MessageController.cs
> +            long[] ids = stringIds.Split('i').Select(x => long.Parse(x)).ToArray();
Try to do it like in link in above comment.

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Models/Message.cs
> +        public DateTime ReceiveDate { get; set; }
ReceivedDate

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Repositories/CrudRepository.cs
>  }
O now there is an EOF marker :), so if you can make one empty line in the end of this file.
You can read more about it here, [EOF article](https://gist.github.com/camh-/1bebfcff1b0f814e9b191edc60d5206b)

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Repositories/CrudRepository.cs
> +        public void DeleteByIds(long[] ids)
Probably can be changed to List<Long> ids if you make suggested changes in controller.

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Repositories/Message/IMessageRepository.cs
> +        public IList<Message> GetAllMessagesFromRange(long bossId, int fromRange, int toRange);
Hmm, two above methods doing the same? Two of them have fromRange and toRange parameters.

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Repositories/Message/MessageRepository.cs
>          }
Ok, IMO, you should make one method from this two above and name it `GetMessagesInRange`. All word is not necessary here 😄. Also, you can make private methods, i.e. to filter message by boss name.

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Repositories/Message/MessageRepository.cs
> +        public int GetMessageToCount(long bossId)
GetMessagesAmount or GetMessagesQuantity for me are better names.

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Services/Authorization/AuthService.cs
> +                    return new string[] { "There is no player with such nick" };
"Wrong nick or password" will be a better message. Why, because person, who want to get someone conditionals will be having less info.

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Services/Authorization/AuthService.cs
> +                    return new string[] { "Wrong password" };
"Wrong nick or password" will be a better message. Why, because person, who want to get someone conditionals will be having less info.

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Services/Authorization/AuthService.cs
> +            try
Strange try catch block for me, I don't get it

2021-07-22 19:45 UTC, krzysztofMi commented on MafiaAPI/Services/Authorization/AuthService.cs
> +                Player player = _playerRepository.GetByNick(user.Nick);
Only this should be rather in try catch block

2021-07-23 05:46 UTC, PatrykMargasinski commented on MafiaAPI/Controllers/BossControler.cs
> +                return BadRequest("Boss with that name not found");
It's not big difference, but I'll change it

2021-07-23 05:48 UTC, PatrykMargasinski commented on MafiaAPI/Controllers/MessageController.cs
> +                .GetAllMessagesToRange(id, fromRange.Value, toRange.Value, bossNameFilter ?? "", onlyUnseen ?? false)
Now I think I should remove old GetAllMessagesTo and change GetAllMessageToRange to "GetAllMessageToRange". There will be only 1 method with many nullable arguments.

2021-07-23 05:49 UTC, PatrykMargasinski commented on MafiaAPI/Repositories/Message/MessageRepository.cs
> +        public int GetMessageToCount(long bossId)
It's "count" because list's method is called "Count" and sql method is called "Count" too

2021-07-23 05:52 UTC, PatrykMargasinski commented on MafiaAPI/Services/Authorization/AuthService.cs
> +                    return new string[] { "There is no player with such nick" };
Look from the honest user side. I would like to make his life as easy as possible. Let him know if he made a typo in the nickname or in the password. Since it has been hash functionality added, the person trying to break in has already difficult enough job.

2021-07-23 05:56 UTC, PatrykMargasinski commented on MafiaAPI/Services/Authorization/AuthService.cs
> +            try
If any exception appears, client has adnotation that something happened.

2021-07-23 05:58 UTC, PatrykMargasinski commented on MafiaAPI/Controllers/MessageController.cs
> +            var content= _securityService.Decrypt(message.Subject)+"\n\n"+
I don't get it

2021-07-23 05:59 UTC, PatrykMargasinski commented on MafiaAPI/Controllers/MessageController.cs
> +        public JsonResult DeleteMessages(string stringIds)
Yeah, it works. That's why I would stay with my solution.

2021-07-23 06:01 UTC, PatrykMargasinski commented on MafiaAPI/Repositories/Message/IMessageRepository.cs
> +        public IList<Message> GetAllMessagesFromRange(long bossId, int fromRange, int toRange);
Not exactly:
GetMessageTo() - get all messages sent to some boss
GetMessageFrom() - get all messages sent from some boss
But, yeah, it can be simplified

2021-07-23 06:03 UTC, PatrykMargasinski commented on MafiaAPI/Repositories/Message/MessageRepository.cs
>          }
Not exactly. I want Sql server to create appropriate query. That's why I can use only methods which are implemented by EF's content

2021-07-23 10:42 UTC, krzysztofMi commented on MafiaAPI/Services/Authorization/AuthService.cs
> +                    return new string[] { "There is no player with such nick" };
Ok, but not always the easy life is good for user if it is coming to secure his data.

2021-07-23 10:44 UTC, krzysztofMi commented on MafiaAPI/Services/Authorization/AuthService.cs
> +            try
Hmm, but I think only `_playerRepository.GetByNick(user.Nick)` can throw an exception.

2021-07-23 10:55 UTC, PatrykMargasinski commented on MafiaAPI/Services/Authorization/AuthService.cs
> +            try
I think everything can throw an exception, so I try-catch everything

2021-07-24 06:00 UTC, merged